spring:
  application:
    name: clouds-integration

  data:
    mongodb:
      uri: mongodb://192.168.99.100:27017/clouds

messages:
  jwtUnauthorizedError: "Sorry, you are not authorized"
  authContextInjectionError: "Could not inject auth to security context"

jwt-provider:
  secret: "secret"
  expirationInMs: 3600000